# Generated by Django 2.1.7 on 2019-03-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20190316_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='mobile',
            field=models.CharField(default='8600611198', max_length=10),
            preserve_default=False,
        ),
    ]
